sonar.projectKey=aceest-devops
sonar.projectName=ACEest DevOps
sonar.projectVersion=1.0.0
sonar.sources=aceest
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=versions/**,docs/**
sonar.sourceEncoding=UTF-8
