apiVersion: v1
kind: Service
metadata:
  name: aceest-blue-green-active
  namespace: aceest-devops
spec:
  selector:
    app: aceest-app
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30081
  type: NodePort
